language: C
compiler: gcc
dist:
 - bionic

#branches:
#  only:
#    master
#    /^v\d+\.\d+(\.\d+)?(-\S*)?$/

addons:
  hosts:
    - travis.local

  sonar:

  apt:
    packages:
      - libmbedtls-dev
      - libconfig-dev
      - libjansson-dev

  sonarcloud:
    organization: "${SONARCLOUD_ORGANIZATION}" # the key of the org you chose at step #3
    token:

jobs:
  include:
    - stage: test
      script:
        git clone ${GITHUB_LIBHTTPSERVER} -b ${TRAVIS_BRANCH} libhttpserver &&
        make defconfig && make AUTHN_OAUTH2=n TINYSVCMDNS=n oldconfig &&
        build-wrapper-linux-x86-64 --out-dir bw-output make DEBUG=y G=1 &&
        make hosttools &&
        LD_LIBRARY_PATH=$PWD/libhttpserver/src:$PWD/libhttpserver/src/httpserver ./tests/run.sh -A -N;
        make gcov &&
        sonar-scanner -D sonar.projectKey=${SONARCLOUD_ORGANIZATION}_ouistiti
    - stage: release
      script:
        git clone ${GITHUB_LIBHTTPSERVER} libhttpserver &&
        make clean &&
        make fullforked_defconfig &&
        make TINYSVCMDNS=n oldconfig &&
        make && mkdir ${PWD}/release &&
        make DESTDIR=${PWD}/release install &&
        pushd ${PWD}/release && tar -czf ../ouistiti-travis.tar.gz . && popd
